name:          PortMidi
version:       0.2.0.0
Cabal-Version: >= 1.8
build-type:    Simple
license:       BSD3
license-file:  LICENSE
maintainer:    Paul H. Liu <paul@thev.net>
             , Olivier Sohn <olivier.sohn@gmail.com>
homepage:      http://github.com/PortMidi/PortMidi
category:      Sound
stability:     experimental
synopsis:      A binding for PortMedia/PortMidi
description:   A Haskell binding for PortMedia/PortMidi
extra-source-files:
        README.txt
        CHANGELOG.md
Library
  exposed-modules: Sound.PortMidi
  other-modules:   Sound.PortMidi.DeviceInfo
  build-depends:   base >= 4.8 && < 5
  extensions:      CPP, ForeignFunctionInterface
  pkgconfig-depends: PortMidi
source-repository head
  type:         git
  location:     https://github.com/PortMidi/PortMidi-haskell
